name = "onchain_jwt"
version = "0.0.0"
license = "GPL-3.0"
description = "Aiken contracts for project 'onchain_jwt'"

[repository]
user = "ctf"
project = "onchain_jwt"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
